# Generated by Django 2.0.3 on 2018-04-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puddle',
            name='is_channel',
            field=models.BooleanField(default=False),
        ),
    ]
